### ISSUE TITLE
[Brainstorming] - Roadmap

### ISSUE THREAD

**Issue by awmatheson** [Azure/aml-registermodel#4]
# Feature brainstorming for GH integration
- [x] Pass model back to artifact in actions
- [x] Make a release flag so that the model will be made into a release automatically. 
- [x] Create a docker image of the model
- [x] Deployment of a model, which has not been trained on AML or with GH Actions

**Comment by marvinbuss** [comment]
Added tasks to individual actions.
